Improve 3
linxGnu/gosmpp pull request #38
Opened 2020-09-17 03:55 UTC by septs

2020-09-17 04:06 UTC, septs commented
![image](https://user-images.githubusercontent.com/3842474/93418891-f5970f00-f8dd-11ea-81b3-67b89634f02e.png)

1. Fix a typo error, `GenerickNack` -> `GenericNack`

2. Use `binary.Read` & `binary.Write` simplify pdu header `Unmarshal ` and `Marshal`.

2020-09-17 12:06 UTC, septs commented
@linxGnu

2020-09-17 13:59 UTC, linxGnu requested changes
Thank you for fixing GenericNack typo. However, I think other optimization should be considered carefully.

2020-09-17 13:59 UTC, linxGnu commented on pdu/PDUHeader.go
> +	_ = binary.Write(b, binary.BigEndian, c)
What happen if we add another field for internal metadata. They will be marshaled to buffer? I don't think we should do that.

2020-09-17 13:59 UTC, linxGnu commented on pdu/PDUHeader.go
> +	err = binary.Read(b, binary.BigEndian, c)
Same reason with Marshaling with binary encoding

2020-09-17 13:59 UTC, linxGnu commented on pdu/PDUHeader.go
> +	_ = h.Unmarshal(NewBuffer(v[:]))
I really want fastest parsing here

2020-09-18 00:11 UTC, linxGnu approved these changes
LGTM. Thank you very much

2020-09-18 00:11 UTC, merged